github_username: raveious

# Build settings
markdown: kramdown
theme: jekyll-theme-merlot

collections:
  characters:
    output: true
  monsters:
    output: true
  weapons:
    output: true

exclude:
  - "docker-compose.yml"
  - "dnd5tools"
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
      race: "human"
      level: 1
      str: 10
      dex: 10
      con: 10
      int: 10
      wis: 10
      cha: 10
  - scope:
      path: ""
      type: "monsters"
    values:
      layout: "monster"
      level: 1
      str: 8
      dex: 8
      con: 8
      int: 8
      wis: 8
      cha: 8
  - scope:
      path: ""
      type: "weapons"
    values:
      layout: "weapon"
